# Generated by Django 4.0 on 2022-01-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_storyiten_body_storyiten_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
